language: node_js
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: X7VZkchR8ayItgVfGu43xDr+AvpYL/Vm5flQMEevp9Y62N7XaFMXTzy8ukjMnMPYhSvtOD2FHCVKlbZ+6bikyRJAdQsdMZ5Ipxx4bw40gDY6IFoOwV/wTJ+CnGOxkjV+JeC2wKSw+/Q4+Ml0Xm5/J2aQha+SigkRr/MhXmZbq9VUyKAAKN9c76r7o1TGCgrxR7zC+oiBeKmoxuhKZxUS4IOfwAl+7NjSk8eki5tbStZri6QCplG7/h8xerGqGa1b8LwceoKq8hctY8r911IEdylagyiryQGsDEg5uQ01yyKHZ4qEKUbFuMvqe/pbrc7U3az2SooDEoksdTUGg5jqS0tOdl25EshRCFi4cGdGknZAuDUMSdhhUcciRTgoHdh4D/MX0A4BYZQ2vplSlzkcgRBptqb4TlUBTqwQpbBKW7cC7vXVyjEkIfIp1BvmEz2w1Xhr3nCO3JUkqJ0ML7zr8TFL/aYVk/7WoDxMm8zFY+cyDwshiMK1rxFVJ1SkDasKCVfB736wQTS4Tu8APyL05ojS3D6MLCHseMkzdR2IhcicZ07NsznpCFn5xln0xH43ZN9vwruuB1MR5lJWlBJvzCcQ42mIIkB7HU3kkQnRYIZK5wvlH24v5EhZl9txAp8C1jrfKSP338PEXqPZGssQIshnNPdnC/myvfOIKCG5gdY=
