language: node_js
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: KG+ko1j5a+wSlbbx8fbHlix4iRrEPI6+mn8VKS+/Iga4dKLp3rvd01HQdIKStY1DmFV4jlKleLqqz75rGp4I8SP91ED2XBOg2vtHTQKYkUw+/b/2vogbExk/bp6m7Z1SQFFk4PUmwyS+e5cl5Bowd+K2Gdf0Of8kfVMPz4gNlX98oQAOedprRqTVjQKAIwZtv75men5VVxppy+3/kGVArL5Pi5rcCkyu2O3qt35o6XL/cX1JT3XulJehAiwY+EzLrYB0bVx1r/UOfHPHO8cJrb7IXSpzYlWwZ99i9KOaxD83gdL5/ZfEm2+d0Tvsev7H410bzxNWUSHebgihQv8OjhNMQXz3I7Fusr6OpisZClKC2IB8ih/UehAH6Tyg11Iv3Dny489CZEruY6D1L/58JeTVeNXuWuQ76CgOXLV5Y+eayFQ34C24/ljEQZ5zQzy2Q7arEE4YfHr4mV3GbixliMLYLoXdb01wn97oxSE5nVBYzhZniNhmpQ/U45y8ppxuGwnxMyZ6mUh9mJpB/MVav5BfcEul7PflJkcGnjuNh88Pnb4ZUuHqteccCsEeSEY1jNgso/FTsBAzVxVyLFAZsxSuK5t5xXYZBv7MyJ2nQe9cLpf33uAdkMblxQLsY2e/ALjsrc40qmGS+ORgdkwtNBsmrZ1g7EUGPqhUtyPQ+Xs=
